### ISSUE TITLE
Issues on https://owi-lab.github.io/py_fatigue/user/examples/07-damage.html

### ISSUE THREAD

**Issue by wweijtje** [OWI-Lab/py_fatigue#3]
An overview of some of the issues on this page:
- It mentions 'Palmgen' instead of 'Palmgren '
- The initial example of a 'constant signal' actually shows a sinoid
- The example using `get_pm` is missing

**Comment by pietrodantuono** [comment]
Resolved

**Comment by pietrodantuono** [comment]
- 'constant signal' to be changed with 'constant fatigue load'
- get_pm example to be added

**Comment by pietrodantuono** [comment]
- 'constant signal' changed with 'constant fatigue load'
- `get_pm` example already available both in noob and in user guide
