### ISSUE TITLE
Cycle count data is assumed to be MPa

### ISSUE THREAD

**Issue by wweijtje** [OWI-Lab/py_fatigue#4]
The input to the CycleCount object is assumed to be in MPa. However this is not documented nor is it enforced.

**Comment by pietrodantuono** [comment]
Resolved by adding the `CycleCount.unit` property.

DONE: when `SNCurve.unit` and `CycleCount.unit` are not compatible, an error is raised.

TODO: raise the same type of error for crack propagation problems.

**Comment by pietrodantuono** [comment]
Done and added proper testing.

Now either `if SNCurve.unit != CycleCount.unit` or `if CycleCount.unit is not in ParisCurve.unit`, an error is raised
